"""Excel 内容比对与数据质量核验系统。"""

from __future__ import annotations

from excel_qc.errors import (
    AmbiguousFieldError,
    ComparisonBlankValueError,
    ComparisonConfigError,
    ComparisonError,
    DuplicateSheetSelectionError,
    EmptySheetSelectionError,
    ExcelQcError,
    FormatConfigError,
    NoFieldSelectedError,
    SelectionError,
    SourceFileNotFoundError,
    StandardBlankValueError,
    StandardConfigError,
    StandardDataError,
    StandardEmptySheetError,
    StandardFieldAmbiguousError,
    StandardFieldNotFoundError,
    StandardMappingConflictError,
    StandardNoDataError,
    StandardSheetNotFoundError,
    UnknownFieldError,
    UnknownSheetError,
    UnsupportedFileTypeError,
    WorkbookReadError,
)
from excel_qc.comparison import compare_standard_mapping
from excel_qc.field_mapping import (
    FieldMappingConfig,
    FieldMappingConfigError,
    FieldMappingEntry,
    FieldMappingError,
    FieldMappingResult,
    FieldMappingStatus,
    FieldMappingSummary,
    FieldMatchRule,
    StandardFieldDefinition,
    WorkbookFieldMappingResult,
    load_field_mapping_config,
    map_sheet_fields,
    map_workbook_fields,
    normalize_field_name,
)
from excel_qc.inspector import inspect_workbook
from excel_qc.loader import load_workbook
from excel_qc.models import (
    CellLocation,
    ComparisonResult,
    ComparisonRowResult,
    ComparisonStatus,
    ComparisonSummary,
    FieldSelection,
    FieldSelectionRequest,
    FieldFormatRule,
    FormatCheckResult,
    FormatIssue,
    FormatSummary,
    FormatValueType,
    MappingCheckConfig,
    SheetSelection,
    StandardColumn,
    StandardDataset,
    StandardDatasetConfig,
    StandardRecord,
    ValidationErrorType,
    ValidationIssue,
    ValidationResult,
    ValidationSource,
    ValidationSummary,
    WorkbookSelection,
)
from excel_qc.profiler import (
    FieldProfile,
    HeaderCandidate,
    ProfileIssue,
    ProfileIssueLevel,
    SheetProfile,
    WorkbookProfile,
    profile_workbook,
)
from excel_qc.selection import select_fields, validate_selection
from excel_qc.standard import import_standard_dataset
from excel_qc.format_check import check_formats
from excel_qc.validation import (
    comparison_result_to_validation_result,
    format_check_result_to_validation_result,
    sort_validation_issues,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousFieldError",
    "CellLocation",
    "ComparisonBlankValueError",
    "ComparisonConfigError",
    "ComparisonError",
    "ComparisonResult",
    "ComparisonRowResult",
    "ComparisonStatus",
    "ComparisonSummary",
    "DuplicateSheetSelectionError",
    "EmptySheetSelectionError",
    "ExcelQcError",
    "NoFieldSelectedError",
    "SelectionError",
    "SourceFileNotFoundError",
    "StandardBlankValueError",
    "StandardColumn",
    "StandardConfigError",
    "StandardDataError",
    "StandardDataset",
    "StandardDatasetConfig",
    "StandardEmptySheetError",
    "StandardFieldAmbiguousError",
    "StandardFieldNotFoundError",
    "StandardMappingConflictError",
    "StandardNoDataError",
    "StandardRecord",
    "StandardSheetNotFoundError",
    "UnknownFieldError",
    "UnknownSheetError",
    "UnsupportedFileTypeError",
    "ValidationErrorType",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSource",
    "ValidationSummary",
    "WorkbookReadError",
    "FieldSelection",
    "FieldSelectionRequest",
    "FieldProfile",
    "FieldFormatRule",
    "FieldMappingConfig",
    "FieldMappingConfigError",
    "FieldMappingEntry",
    "FieldMappingError",
    "FieldMappingResult",
    "FieldMappingStatus",
    "FieldMappingSummary",
    "FieldMatchRule",
    "FormatCheckResult",
    "FormatConfigError",
    "FormatIssue",
    "FormatSummary",
    "FormatValueType",
    "HeaderCandidate",
    "MappingCheckConfig",
    "ProfileIssue",
    "ProfileIssueLevel",
    "SheetSelection",
    "SheetProfile",
    "StandardFieldDefinition",
    "WorkbookSelection",
    "WorkbookProfile",
    "WorkbookFieldMappingResult",
    "compare_standard_mapping",
    "check_formats",
    "comparison_result_to_validation_result",
    "format_check_result_to_validation_result",
    "import_standard_dataset",
    "inspect_workbook",
    "load_workbook",
    "load_field_mapping_config",
    "map_sheet_fields",
    "map_workbook_fields",
    "normalize_field_name",
    "profile_workbook",
    "select_fields",
    "sort_validation_issues",
    "validate_selection",
    "__version__",
]
